site_name: Typescript
site_url: https://scriptdev.ru/
site_description: Справочник Typescript-разработчика с примерами кода
site_author: scriptdev.ru
copyright: (C) 2021-2023, Справочник разработчика Typescript с примерами кода

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/scriptdev.ru'

theme:
    name: material
    custom_dir: overrides
    # Don't include MkDocs' JavaScript
    # include_search_page: false
    # search_index_only: true

    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Тёмная тема
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: Светлая тема
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
        - navigation.top
        - content.action.edit
    favicon: ts.svg
    logo: ts.svg

extra:
    generator: false
    social:
        - icon: fontawesome/brands/html5
          link: 'https://hcdev.ru/'
          name: HTML and CSS docs
        - icon: fontawesome/brands/js
          link: 'https://scriptdev.ru/'
          name: Javascript
        - icon: fontawesome/brands/angular
          link: 'https://angdev.ru/'
          name: Angular docs
        - icon: fontawesome/brands/react
          link: 'https://reactdev.ru/'
          name: React docs
        - icon: fontawesome/brands/node-js
          link: 'https://nodejsdev.ru/'
          name: Node.js docs
        - icon: fontawesome/brands/python
          link: 'https://py3dev.ru/'
          name: Python 3 docs
        - icon: fontawesome/solid/code
          link: 'https://xsltdev.ru/'
          name: XSLT docs

#google_analytics:
#    - UA-34215161-1
#    - auto

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.keys

plugins:
    - search:
          lang:
              - ru
              - en
    - awesome-pages
    # - section-index
    - social

extra_css:
    - '/assets/stylesheets/styles.css?3'
